config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'api'

urlpatterns = [
    path('', views.companies_view),
    path('add_employee/<int:id>', views.add_employee),
    
]

main/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100)

class Employee(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    comment = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from main.models import Company, Employee

# Create your views here.


def companies_view(request):
    
    companies = Company.objects.all()
    
    parameters = {
        "companies": companies
        }
    
    return render(request, 'companies.html', parameters)

def add_employee(request, id):
    
    employees = Employee.objects.filter(company=None)
    
    parameters = {
        "employees": employees
    }
    
    
    if request.method == "POST":
        employee_id = request.POST.get('employee')
        
        company = Company.objects.get(id=id)
        employee = Employee.objects.get(id=employee_id)
        
        employee.company = company
        
        employee.save()
        
        print("=============================Everything done")
        return redirect("/")
    
    return render(request, "add_employee.html", parameters)

templates/add_employee.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Employee</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>

    <div class="container my-5">

        <form method="POST">
            {% csrf_token %}
            <label for="employee">Select an employee:</label>
            <select name="employee" id="employee">
                {% for employee in employees %}
                    <option value="{{ employee.id }}">{{ employee.first_name }} {{ employee.last_name }}</option>
                {% endfor %}
            </select>
            <br>
            <input class="btn btn-outline-success my-4" type="submit" value="Add Employee">
        </form>
            


    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

templates/companies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Companies List</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
<table>
    <tr>
        <th style="width: 20%;">Company</th>
        <th>Employees</th>
    </tr>
    {% for company in companies %}
    <tr>
        <td>{{ company.name }} <a href="add_employee/{{ company.id }}">(Add Employee)</a></td>
        <td>
            {{ company.employee_set.all|join:', ' }}
        </td>
    </tr>
    {% endfor %}
</table>
</body>
</html>